"use strict";

const projects = [
  {
    id: 1214,
    class: "card",
    cover: "./images/entertainment-preview.jpg",
    title: "Entertainment Web App",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "JSON",
    },
    netlify: "https://entertainment-app-beka.netlify.app",
    github: "https://github.com/jalagania/entertainment-app",
  },
  {
    id: 1,
    class: "card",
    cover: "./images/countries-preview.jpg",
    title: "REST Countries API",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "API",
      json: "",
    },
    netlify: "https://rest-countries-api-beka.netlify.app",
    github: "https://github.com/jalagania/rest-countries-api",
  },
  {
    id: 2,
    class: "card",
    cover: "./images/comments-preview.jpg",
    title: "Interactive Comments",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "JSON",
    },
    netlify: "https://interactive-comments-beka.netlify.app",
    github: "https://github.com/jalagania/interactive-comments",
  },
  {
    id: 3,
    class: "card",
    cover: "./images/ttt-preview.jpg",
    title: "Tic Tac Toe",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://tic-tac-toe-beka.netlify.app",
    github: "https://github.com/jalagania/tic-tac-toe",
  },
  {
    id: 4,
    class: "card",
    cover: "./images/rps-preview.jpg",
    title: "Rock Paper Scissors +",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://rock-paper-scissors-beka.netlify.app",
    github: "https://github.com/jalagania/rock-paper-scissors",
  },
  {
    id: 5,
    class: "card",
    cover: "./images/multistep-preview.jpg",
    title: "Multi-step Form",
    tools: {
      html: "HTML",
      css: "TAILWIND",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://multistep-form-beka.netlify.app",
    github: "https://github.com/jalagania/multistep-form",
  },
  {
    id: 6,
    class: "card",
    cover: "./images/calculator-preview.jpg",
    title: "PEMDAS Calculator",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://pemdas-calculator-beka.netlify.app",
    github: "https://github.com/jalagania/pemdas-calculator",
  },
  {
    id: 7,
    class: "card",
    cover: "./images/ecommerce-preview.jpg",
    title: "Ecommerce Product Page",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://ecommerce-product-page-beka.netlify.app",
    github: "https://github.com/jalagania/ecommerce-product-page",
  },
  {
    id: 8,
    class: "card",
    cover: "./images/joblist-preview.jpg",
    title: "Job List Filter",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "JSON",
    },
    netlify: "https://job-list-filter-beka.netlify.app",
    github: "https://github.com/jalagania/job-list-filter",
  },
  {
    id: 9,
    class: "card",
    cover: "./images/todo-preview.jpg",
    title: "Todo List",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://todo-list-beka.netlify.app",
    github: "https://github.com/jalagania/todo-list",
  },
  {
    id: 10,
    class: "card",
    cover: "./images/crowdfund-preview.jpg",
    title: "Crowdfunding Page",
    tools: {
      html: "HTML",
      css: "TAILWIND",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://crowdfunding-page-beka.netlify.app",
    github: "https://github.com/jalagania/crowdfunding-page",
  },
  {
    id: 11,
    class: "card",
    cover: "./images/shortly-preview.jpg",
    title: "URL Shortener",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "API",
      json: "",
    },
    netlify: "https://url-shortener-beka.netlify.app",
    github: "https://github.com/jalagania/url-shortener",
  },
  {
    id: 12,
    class: "card",
    cover: "./images/ip-preview.jpg",
    title: "IP Address Tracker",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "API",
      json: "",
    },
    netlify: "https://ip-address-tracker-beka.netlify.app",
    github: "https://github.com/jalagania/ip-address-tracker",
  },
  {
    id: 13,
    class: "card",
    cover: "./images/card-preview.jpg",
    title: "Interactive Card",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://interactive-schmard-beka.netlify.app",
    github: "https://github.com/jalagania/interactive-card",
  },
  {
    id: 14,
    class: "card",
    cover: "./images/tip-preview.jpg",
    title: "Tip Calculator",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://tip-calculator-beka.netlify.app",
    github: "https://github.com/jalagania/tip-calculator",
  },
  {
    id: 15,
    class: "card",
    cover: "./images/timer-preview.jpg",
    title: "Countdown Timer",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://countdown-timer-beka.netlify.app",
    github: "https://github.com/jalagania/countdown-timer",
  },
  {
    id: 16,
    class: "card",
    cover: "./images/advice-preview.jpg",
    title: "Advice Generator",
    tools: {
      html: "HTML",
      css: "CSS",
      js: "",
      react: "REACT",
      api: "",
      json: "",
    },
    netlify: "https://advice-generator-beka.netlify.app",
    github: "https://github.com/jalagania/advice-generator",
  },
];
